"""
Feast Feature Definitions for Email Intelligence
Defines all 291+ features from email enrichment pipeline

Version: 4.1.0
"""

from datetime import timedelta
from feast import Entity, FeatureView, Field, FileSource
from feast.types import String, Int64, Float64, Bool, UnixTimestamp


# ========== ENTITY DEFINITION ==========

email_entity = Entity(
    name="email",
    description="Email address as primary entity",
    value_type=String
)


# ========== DATA SOURCE ==========

# Parquet files generated by feast_integration.py
email_features_source = FileSource(
    name="email_features_source",
    path="data/email_features.parquet",
    timestamp_field="event_timestamp",
)


# ========== FEATURE VIEW: IDENTITY & VALIDATION ==========

identity_features = FeatureView(
    name="identity_features",
    entities=[email_entity],
    ttl=timedelta(days=90),  # Identity data stable for 90 days
    schema=[
        # Email validation (5)
        Field(name="is_valid_format", dtype=Bool),
        Field(name="is_free_provider", dtype=Bool),
        Field(name="is_disposable", dtype=Bool),
        Field(name="is_corporate", dtype=Bool),
        Field(name="provider_type", dtype=String),

        # Name extraction (8)
        Field(name="has_name_in_email", dtype=Bool),
        Field(name="has_full_name", dtype=Bool),
        Field(name="has_numbers", dtype=Bool),
        Field(name="has_special_chars", dtype=Bool),
        Field(name="name_length", dtype=Int64),
        Field(name="is_professional_format", dtype=Bool),
        Field(name="name_parts_count", dtype=Int64),
        Field(name="username_entropy", dtype=Float64),

        # Domain analysis (12)
        Field(name="domain_length", dtype=Int64),
        Field(name="has_subdomain", dtype=Bool),
        Field(name="tld_type", dtype=String),
        Field(name="is_common_tld", dtype=Bool),
        Field(name="domain_age_days", dtype=Int64),
        Field(name="domain_registered", dtype=Bool),
        Field(name="has_mx_records", dtype=Bool),
        Field(name="mx_count", dtype=Int64),
        Field(name="domain_rank", dtype=Int64),
        Field(name="is_fortune500", dtype=Bool),
        Field(name="is_startup", dtype=Bool),
        Field(name="is_educational", dtype=Bool),
    ],
    source=email_features_source,
    tags={"category": "identity"},
)


# ========== FEATURE VIEW: SOCIAL & PROFESSIONAL ==========

social_features = FeatureView(
    name="social_features",
    entities=[email_entity],
    ttl=timedelta(days=30),  # Social data refreshed monthly
    schema=[
        # GitHub (20)
        Field(name="has_github", dtype=Bool),
        Field(name="github_username", dtype=String),
        Field(name="github_followers", dtype=Int64),
        Field(name="github_following", dtype=Int64),
        Field(name="github_repos", dtype=Int64),
        Field(name="github_stars", dtype=Int64),
        Field(name="github_forks", dtype=Int64),
        Field(name="github_contributions", dtype=Int64),
        Field(name="github_account_age_days", dtype=Int64),
        Field(name="github_has_bio", dtype=Bool),
        Field(name="github_has_company", dtype=Bool),
        Field(name="github_has_location", dtype=Bool),
        Field(name="github_has_blog", dtype=Bool),
        Field(name="github_hireable", dtype=Bool),
        Field(name="github_activity_score", dtype=Float64),
        Field(name="github_influence_score", dtype=Float64),
        Field(name="github_primary_language", dtype=String),
        Field(name="github_languages_count", dtype=Int64),
        Field(name="github_verified", dtype=Bool),
        Field(name="github_profile_complete", dtype=Float64),

        # Gravatar (5)
        Field(name="has_gravatar", dtype=Bool),
        Field(name="gravatar_profile_complete", dtype=Float64),
        Field(name="gravatar_verified", dtype=Bool),
        Field(name="gravatar_has_avatar", dtype=Bool),
        Field(name="gravatar_display_name_set", dtype=Bool),

        # Social presence (10)
        Field(name="social_platforms_count", dtype=Int64),
        Field(name="has_twitter", dtype=Bool),
        Field(name="has_linkedin", dtype=Bool),
        Field(name="has_facebook", dtype=Bool),
        Field(name="social_activity_level", dtype=String),
        Field(name="professional_network_size", dtype=Int64),
        Field(name="social_influence_score", dtype=Float64),
        Field(name="online_presence_strength", dtype=Float64),
        Field(name="digital_footprint_age_days", dtype=Int64),
        Field(name="cross_platform_consistency", dtype=Float64),
    ],
    source=email_features_source,
    tags={"category": "social"},
)


# ========== FEATURE VIEW: SECURITY & QUALITY ==========

security_features = FeatureView(
    name="security_features",
    entities=[email_entity],
    ttl=timedelta(days=7),  # Security data refreshed weekly
    schema=[
        # Breach data (10)
        Field(name="has_breaches", dtype=Bool),
        Field(name="breach_count", dtype=Int64),
        Field(name="breach_severity_max", dtype=String),
        Field(name="breach_data_classes", dtype=Int64),
        Field(name="breach_most_recent_days", dtype=Int64),
        Field(name="breach_oldest_days", dtype=Int64),
        Field(name="breach_verified_count", dtype=Int64),
        Field(name="breach_sensitive_count", dtype=Int64),
        Field(name="pwned_risk_score", dtype=Float64),
        Field(name="credentials_leaked", dtype=Bool),

        # Email quality (15)
        Field(name="deliverable", dtype=Bool),
        Field(name="deliverability_score", dtype=Float64),
        Field(name="is_role_account", dtype=Bool),
        Field(name="is_catch_all", dtype=Bool),
        Field(name="smtp_valid", dtype=Bool),
        Field(name="syntax_valid", dtype=Bool),
        Field(name="dns_valid", dtype=Bool),
        Field(name="spam_trap", dtype=Bool),
        Field(name="spam_score", dtype=Float64),
        Field(name="reputation_score", dtype=Float64),
        Field(name="blacklisted", dtype=Bool),
        Field(name="suspicious", dtype=Bool),
        Field(name="malicious_activity", dtype=Bool),
        Field(name="abuse_reported", dtype=Bool),
        Field(name="data_quality_score", dtype=Float64),
    ],
    source=email_features_source,
    tags={"category": "security"},
)


# ========== FEATURE VIEW: BEHAVIORAL ==========

behavioral_features = FeatureView(
    name="behavioral_features",
    entities=[email_entity],
    ttl=timedelta(days=1),  # Behavioral data updated daily
    schema=[
        # Activity patterns (15)
        Field(name="activity_frequency", dtype=String),
        Field(name="last_seen_days_ago", dtype=Int64),
        Field(name="first_seen_days_ago", dtype=Int64),
        Field(name="usage_duration_days", dtype=Int64),
        Field(name="sessions_count", dtype=Int64),
        Field(name="avg_session_duration_min", dtype=Float64),
        Field(name="peak_activity_hour", dtype=Int64),
        Field(name="active_days_count", dtype=Int64),
        Field(name="weekend_activity_ratio", dtype=Float64),
        Field(name="night_activity_ratio", dtype=Float64),
        Field(name="activity_consistency_score", dtype=Float64),
        Field(name="engagement_level", dtype=String),
        Field(name="churned", dtype=Bool),
        Field(name="days_since_last_activity", dtype=Int64),
        Field(name="lifetime_value_estimate", dtype=Float64),

        # Device & Browser (10)
        Field(name="device_types_count", dtype=Int64),
        Field(name="primary_device_type", dtype=String),
        Field(name="browser_types_count", dtype=Int64),
        Field(name="os_types_count", dtype=Int64),
        Field(name="mobile_usage_ratio", dtype=Float64),
        Field(name="desktop_usage_ratio", dtype=Float64),
        Field(name="uses_modern_browser", dtype=Bool),
        Field(name="uses_vpn", dtype=Bool),
        Field(name="device_fingerprint_changes", dtype=Int64),
        Field(name="suspicious_device_pattern", dtype=Bool),
    ],
    source=email_features_source,
    tags={"category": "behavioral"},
)


# ========== FEATURE VIEW: TECHNICAL & GEO ==========

technical_features = FeatureView(
    name="technical_features",
    entities=[email_entity],
    ttl=timedelta(days=7),
    schema=[
        # IP & Geo (20)
        Field(name="ip_country_code", dtype=String),
        Field(name="ip_city", dtype=String),
        Field(name="ip_region", dtype=String),
        Field(name="ip_continent", dtype=String),
        Field(name="ip_timezone", dtype=String),
        Field(name="ip_latitude", dtype=Float64),
        Field(name="ip_longitude", dtype=Float64),
        Field(name="ip_is_proxy", dtype=Bool),
        Field(name="ip_is_vpn", dtype=Bool),
        Field(name="ip_is_tor", dtype=Bool),
        Field(name="ip_is_datacenter", dtype=Bool),
        Field(name="ip_is_mobile", dtype=Bool),
        Field(name="ip_risk_score", dtype=Float64),
        Field(name="ip_abuse_score", dtype=Float64),
        Field(name="isp_name", dtype=String),
        Field(name="asn_number", dtype=Int64),
        Field(name="connection_type", dtype=String),
        Field(name="locations_count", dtype=Int64),
        Field(name="location_consistency_score", dtype=Float64),
        Field(name="geo_velocity_kmh", dtype=Float64),
    ],
    source=email_features_source,
    tags={"category": "technical"},
)


# ========== FEATURE VIEW: COMMERCIAL API DATA ==========

commercial_features = FeatureView(
    name="commercial_features",
    entities=[email_entity],
    ttl=timedelta(days=7),
    schema=[
        # Hunter.io (13)
        Field(name="hunter_deliverable", dtype=Bool),
        Field(name="hunter_score", dtype=Float64),
        Field(name="hunter_disposable", dtype=Bool),
        Field(name="hunter_webmail", dtype=Bool),
        Field(name="hunter_accept_all", dtype=Bool),
        Field(name="hunter_mx_records", dtype=Bool),
        Field(name="hunter_smtp_check", dtype=Bool),
        Field(name="hunter_gibberish", dtype=Bool),
        Field(name="hunter_block", dtype=Bool),
        Field(name="hunter_sources_count", dtype=Int64),
        Field(name="domain_emails_found", dtype=Int64),
        Field(name="domain_has_pattern", dtype=Bool),
        Field(name="domain_has_social", dtype=Bool),

        # EmailRep.io (15)
        Field(name="emailrep_reputation_score", dtype=Float64),
        Field(name="emailrep_suspicious", dtype=Bool),
        Field(name="emailrep_references", dtype=Int64),
        Field(name="emailrep_blacklisted", dtype=Bool),
        Field(name="emailrep_malicious_activity", dtype=Bool),
        Field(name="emailrep_credentials_leaked", dtype=Bool),
        Field(name="emailrep_data_breach", dtype=Bool),
        Field(name="emailrep_spam_detected", dtype=Bool),
        Field(name="emailrep_profiles_count", dtype=Int64),
        Field(name="emailrep_days_since_first_seen", dtype=Int64),
        Field(name="emailrep_days_since_last_seen", dtype=Int64),
        Field(name="emailrep_domain_exists", dtype=Bool),
        Field(name="emailrep_domain_reputation", dtype=String),
        Field(name="emailrep_new_domain", dtype=Bool),
        Field(name="emailrep_domain_days_since_creation", dtype=Int64),

        # Clearbit (12)
        Field(name="clearbit_person_found", dtype=Bool),
        Field(name="clearbit_person_name", dtype=String),
        Field(name="clearbit_person_title", dtype=String),
        Field(name="clearbit_person_seniority", dtype=String),
        Field(name="clearbit_company_found", dtype=Bool),
        Field(name="clearbit_company_name", dtype=String),
        Field(name="clearbit_company_domain", dtype=String),
        Field(name="clearbit_company_employees", dtype=Int64),
        Field(name="clearbit_company_funding", dtype=Float64),
        Field(name="clearbit_company_industry", dtype=String),
        Field(name="clearbit_company_tech_stack_count", dtype=Int64),
        Field(name="clearbit_enrichment_confidence", dtype=Float64),
    ],
    source=email_features_source,
    tags={"category": "commercial"},
)


# ========== FEATURE VIEW: DERIVED SCORES ==========

derived_scores = FeatureView(
    name="derived_scores",
    entities=[email_entity],
    ttl=timedelta(days=7),
    schema=[
        # Composite scores (25)
        Field(name="identity_strength_score", dtype=Float64),
        Field(name="trust_score", dtype=Float64),
        Field(name="security_risk_score", dtype=Float64),
        Field(name="fraud_risk_score", dtype=Float64),
        Field(name="engagement_score", dtype=Float64),
        Field(name="quality_score", dtype=Float64),
        Field(name="completeness_score", dtype=Float64),
        Field(name="verification_level", dtype=String),
        Field(name="user_tier", dtype=String),
        Field(name="lead_score", dtype=Float64),
        Field(name="conversion_probability", dtype=Float64),
        Field(name="churn_risk_score", dtype=Float64),
        Field(name="bot_probability", dtype=Float64),
        Field(name="persona_cluster", dtype=String),
        Field(name="value_segment", dtype=String),
        Field(name="risk_tier", dtype=String),
        Field(name="authenticity_score", dtype=Float64),
        Field(name="professionalism_score", dtype=Float64),
        Field(name="social_proof_score", dtype=Float64),
        Field(name="developer_score", dtype=Float64),
        Field(name="influencer_score", dtype=Float64),
        Field(name="enterprise_fit_score", dtype=Float64),
        Field(name="data_freshness_score", dtype=Float64),
        Field(name="overall_confidence_score", dtype=Float64),
        Field(name="ml_ready", dtype=Bool),
    ],
    source=email_features_source,
    tags={"category": "derived"},
)
