"""
Feature Explorer Page
Browse and understand all 291 features available
"""

import streamlit as st
import pandas as pd

st.set_page_config(
    page_title="Feature Explorer",
    page_icon="🔬",
    layout="wide"
)

st.title("🔬 Feature Explorer")
st.markdown("Browse and understand all 291 features generated by the enrichment pipeline")

# Feature catalog
FEATURE_CATALOG = {
    "Identity & Validation (45 features)": {
        "description": "Email format, provider, domain analysis, name extraction",
        "ttl": "90 days",
        "features": [
            ("is_valid_format", "bool", "Email has valid RFC format"),
            ("is_free_provider", "bool", "Email is from free provider (Gmail, Yahoo, etc)"),
            ("is_disposable", "bool", "Disposable/temporary email detected"),
            ("is_corporate", "bool", "Corporate/business email"),
            ("provider_type", "string", "Type of email provider"),
            ("has_name_in_email", "bool", "Contains human name"),
            ("has_full_name", "bool", "Has first and last name"),
            ("is_professional_format", "bool", "Professional email pattern"),
            ("domain_length", "int", "Length of domain name"),
            ("has_subdomain", "bool", "Has subdomain"),
            ("tld_type", "string", "Top-level domain type"),
            ("is_common_tld", "bool", "Common TLD (.com, .org, etc)"),
            ("domain_age_days", "int", "Domain age in days"),
            ("has_mx_records", "bool", "Domain has MX records"),
            ("mx_count", "int", "Number of MX records"),
        ]
    },
    "Social & Professional (60 features)": {
        "description": "GitHub activity, social presence, professional signals",
        "ttl": "30 days",
        "features": [
            ("has_github", "bool", "GitHub profile found"),
            ("github_username", "string", "GitHub username"),
            ("github_followers", "int", "GitHub followers count"),
            ("github_following", "int", "Following count"),
            ("github_repos", "int", "Public repositories"),
            ("github_stars", "int", "Total stars received"),
            ("github_forks", "int", "Total forks"),
            ("github_contributions", "int", "Contribution count"),
            ("github_account_age_days", "int", "Account age"),
            ("github_activity_score", "float", "Activity level (0-1)"),
            ("github_influence_score", "float", "Influence metric (0-1)"),
            ("has_gravatar", "bool", "Gravatar profile exists"),
            ("social_platforms_count", "int", "Platforms found"),
            ("has_twitter", "bool", "Twitter profile found"),
            ("has_linkedin", "bool", "LinkedIn profile found"),
        ]
    },
    "Security & Quality (35 features)": {
        "description": "Data breaches, spam detection, reputation",
        "ttl": "7 days",
        "features": [
            ("has_breaches", "bool", "Found in data breaches"),
            ("breach_count", "int", "Number of breaches"),
            ("breach_severity_max", "string", "Highest breach severity"),
            ("pwned_risk_score", "float", "Breach risk score (0-1)"),
            ("credentials_leaked", "bool", "Credentials exposed"),
            ("deliverable", "bool", "Email is deliverable"),
            ("deliverability_score", "float", "Deliverability (0-1)"),
            ("smtp_valid", "bool", "SMTP validation passed"),
            ("spam_trap", "bool", "Spam trap detected"),
            ("spam_score", "float", "Spam likelihood (0-1)"),
            ("reputation_score", "float", "Email reputation (0-1)"),
            ("blacklisted", "bool", "On email blacklists"),
            ("suspicious", "bool", "Suspicious patterns"),
            ("malicious_activity", "bool", "Malicious activity detected"),
        ]
    },
    "Behavioral (40 features)": {
        "description": "Activity patterns, engagement metrics, device fingerprinting",
        "ttl": "1 day",
        "features": [
            ("sessions_count", "int", "Total sessions"),
            ("avg_session_duration_min", "float", "Average session length"),
            ("last_seen_days_ago", "int", "Days since last seen"),
            ("first_seen_days_ago", "int", "Days since first seen"),
            ("active_days_count", "int", "Number of active days"),
            ("engagement_score", "float", "Engagement level (0-1)"),
            ("churned", "bool", "User has churned"),
            ("device_types_count", "int", "Unique devices used"),
            ("browser_types_count", "int", "Browsers used"),
            ("mobile_usage_ratio", "float", "Mobile vs desktop"),
            ("weekend_activity_ratio", "float", "Weekend activity"),
            ("night_activity_ratio", "float", "Night-time activity"),
        ]
    },
    "Technical & Geo (30 features)": {
        "description": "IP geolocation, network analysis, connection type",
        "ttl": "7 days",
        "features": [
            ("ip_country_code", "string", "Country code"),
            ("ip_city", "string", "City name"),
            ("ip_region", "string", "Region/state"),
            ("ip_timezone", "string", "Timezone"),
            ("ip_latitude", "float", "Latitude"),
            ("ip_longitude", "float", "Longitude"),
            ("ip_is_proxy", "bool", "Proxy detected"),
            ("ip_is_vpn", "bool", "VPN detected"),
            ("ip_is_tor", "bool", "Tor network"),
            ("ip_is_datacenter", "bool", "Datacenter IP"),
            ("ip_risk_score", "float", "IP risk level (0-1)"),
            ("isp_name", "string", "ISP name"),
            ("connection_type", "string", "Connection type"),
            ("locations_count", "int", "Unique locations"),
        ]
    },
    "Commercial APIs (56 features)": {
        "description": "Hunter.io, EmailRep, Clearbit enrichment",
        "ttl": "7 days",
        "features": [
            ("hunter_deliverable", "bool", "Hunter deliverable"),
            ("hunter_score", "float", "Hunter quality score"),
            ("hunter_disposable", "bool", "Hunter disposable check"),
            ("hunter_sources_count", "int", "Times seen online"),
            ("emailrep_reputation_score", "float", "EmailRep score"),
            ("emailrep_suspicious", "bool", "Flagged as suspicious"),
            ("emailrep_malicious_activity", "bool", "Malicious flags"),
            ("clearbit_person_found", "bool", "Person data found"),
            ("clearbit_company_found", "bool", "Company data found"),
            ("clearbit_company_employees", "int", "Company size"),
        ]
    },
    "Derived Scores (25 features)": {
        "description": "Composite scores and ML-ready metrics",
        "ttl": "7 days",
        "features": [
            ("trust_score", "float", "Overall trust (0-1)"),
            ("identity_strength_score", "float", "Identity completeness (0-1)"),
            ("security_risk_score", "float", "Security risk (0-1)"),
            ("fraud_risk_score", "float", "Fraud likelihood (0-1)"),
            ("engagement_score", "float", "Activity engagement (0-1)"),
            ("quality_score", "float", "Data quality (0-1)"),
            ("lead_score", "float", "Lead quality (0-1)"),
            ("conversion_probability", "float", "Conversion likelihood (0-1)"),
            ("churn_risk_score", "float", "Churn risk (0-1)"),
            ("bot_probability", "float", "Bot likelihood (0-1)"),
            ("authenticity_score", "float", "Authenticity (0-1)"),
            ("professionalism_score", "float", "Professional signal (0-1)"),
            ("social_proof_score", "float", "Social presence (0-1)"),
            ("developer_score", "float", "Developer likelihood (0-1)"),
        ]
    }
}

# Sidebar - Category Filter
st.sidebar.header("Filter Features")
selected_categories = st.sidebar.multiselect(
    "Categories",
    list(FEATURE_CATALOG.keys()),
    default=list(FEATURE_CATALOG.keys())
)

search_query = st.sidebar.text_input("🔍 Search features", "")

# Main content
st.subheader("📋 Feature Categories")

total_features = sum(len(cat["features"]) for cat in FEATURE_CATALOG.values())
st.metric("Total Features Available", total_features)

st.divider()

# Display features by category
for category_name, category_data in FEATURE_CATALOG.items():
    if category_name not in selected_categories:
        continue

    with st.expander(f"**{category_name}**", expanded=False):
        st.markdown(f"**Description**: {category_data['description']}")
        st.markdown(f"**TTL**: {category_data['ttl']}")

        st.markdown("#### Features")

        # Create DataFrame for this category
        features_df = pd.DataFrame(
            category_data['features'],
            columns=['Feature Name', 'Type', 'Description']
        )

        # Apply search filter
        if search_query:
            mask = features_df['Feature Name'].str.contains(search_query, case=False) | \
                   features_df['Description'].str.contains(search_query, case=False)
            features_df = features_df[mask]

        if not features_df.empty:
            st.dataframe(
                features_df,
                use_container_width=True,
                hide_index=True
            )
        else:
            st.info("No features match your search")

st.divider()

# Feature Statistics
st.subheader("📊 Feature Statistics")

col1, col2, col3 = st.columns(3)

with col1:
    st.metric("Total Categories", len(FEATURE_CATALOG))

with col2:
    bool_features = sum(
        1 for cat in FEATURE_CATALOG.values()
        for _, ftype, _ in cat['features']
        if ftype == 'bool'
    )
    st.metric("Boolean Features", bool_features)

with col3:
    numeric_features = sum(
        1 for cat in FEATURE_CATALOG.values()
        for _, ftype, _ in cat['features']
        if ftype in ['int', 'float']
    )
    st.metric("Numeric Features", numeric_features)

# Feature Type Distribution
st.subheader("📈 Feature Type Distribution")

feature_types = {}
for cat_data in FEATURE_CATALOG.values():
    for _, ftype, _ in cat_data['features']:
        feature_types[ftype] = feature_types.get(ftype, 0) + 1

type_df = pd.DataFrame({
    'Type': list(feature_types.keys()),
    'Count': list(feature_types.values())
})

st.bar_chart(type_df.set_index('Type'))

# Use Cases
st.divider()
st.subheader("💡 Common Use Cases")

use_cases = {
    "Fraud Detection": [
        "trust_score", "fraud_risk_score", "security_risk_score",
        "ip_is_proxy", "has_breaches", "suspicious"
    ],
    "Lead Scoring": [
        "lead_score", "conversion_probability", "engagement_score",
        "is_corporate", "has_github", "professionalism_score"
    ],
    "User Segmentation": [
        "developer_score", "social_proof_score", "engagement_score",
        "quality_score", "identity_strength_score"
    ],
    "Bot Detection": [
        "bot_probability", "authenticity_score", "device_types_count",
        "engagement_score", "activity_consistency_score"
    ]
}

selected_use_case = st.selectbox("Select Use Case", list(use_cases.keys()))

st.markdown(f"**Recommended features for {selected_use_case}:**")
for feature in use_cases[selected_use_case]:
    st.markdown(f"- `{feature}`")

# Export feature list
st.divider()
st.subheader("📥 Export")

if st.button("Export Feature List as CSV"):
    all_features = []
    for cat_name, cat_data in FEATURE_CATALOG.items():
        for feature_name, ftype, description in cat_data['features']:
            all_features.append({
                'Category': cat_name,
                'Feature': feature_name,
                'Type': ftype,
                'Description': description,
                'TTL': cat_data['ttl']
            })

    export_df = pd.DataFrame(all_features)
    csv = export_df.to_csv(index=False)

    st.download_button(
        "Download CSV",
        csv,
        file_name="email_intelligence_features.csv",
        mime="text/csv"
    )
